from dataclasses import dataclass
from cryosparc.tools import CryoSPARC

@dataclass
class VisConfig:
    """
    Configuration object for VisDataset
    
    Attributes
    ----------
    cs: cryosparc.tools.CryoSPARC
        A CryoSPARC object. Used to fetch data from a CS instance.
    project_uid: str
        A project UID. Prefix with P, like "P123".
    base_mic: tuple[str]|None
        A tuple of the JUID and title for the base micrographs. Like ("J123", "micrographs").
    denoised_mic: tuple[str]|None
        A tuple of the JUID and title for the denoised micrographs. Like ("J123", "exposures").
    junk_annotation_mic: tuple[str]|None
        A tuple of the JUID and title for junk-annotated micrographs. Like ("J123", "exposures").
    particles_juid: str
        The job UID from which particle coordinates and statistics are pulled. This could
        be any job with a particles output, like Homogeneous Refinement or 2D Classification.
        Prepend with J, like "J789"
    particles_title: str, default "particles"
        Output title of the particles from the particles source job. Most often, this is
        simply "particles", but it can be e.g., "particles_selected".
    figsize: tuple, default (12, 12)
        Size of the matplotlib figures generated by the class.
    mic_lp_filter_res: float, default 20.0
        Lowpass filter applied to the micrograph, in angstroms.
    mic_uid: int or None, default None
        If None, no micrograph MRC is initially downloaded. When this parameter is set, the micrograph
        is downloaded and the particles filtered to just that micrograph.
    mic_index: int or None, default None
        Specify an index instead of a micrograph UID. Note that it is not guaranteed that micrographs will
        be in the same order in all datasets, so UID should be preferred.
    download_size: bool, default True
        Final shape in pixels of downloaded micrographs
    crop_slice: list or None, default None
        If given, the list is treated as a slice for cropping the micrograph, with elements [0:1, 2:3]
    class_av_title: str or None, default None
        Class average title. Default "class_averages" or "templates_selected", depending on the job type
    class_selection: list or None, default None
        A list of class average inidces to select.
    """

    # base
    cs:CryoSPARC
    project_uid:str
    
    base_mic_spec:tuple[str, str]|None = None
    denoised_mic_spec:tuple[str, str]|None = None
    junk_annotation_spec:tuple[str, str]|None = None
    mic_uid:None|int = None
    mic_index:None|int = None
    downsample_size:None|int = None
    crop_slice:None|list = None
    download_mic:bool = True

    particles_juid:None|str = None
    particles_title:str = "particles"
    iteration:str|int = "F"

    figsize:tuple = (8, 8)
    mic_lp_filter_res:float = 20.0

    # 2D Classification / Selection
    class_av_title:None|str = None
    class_selection:None|list = None
    class_av_version:None|str|int = None

    def copy(self, updates:dict = {}):
        copy_dict = self.__dict__
        copy_dict.update(updates)
        return VisConfig(**copy_dict)